version: '3.8'

services:
  server:
    build: ./
    ports:
      - '80:3000'
    environment:
      DB_PASS: password
      MYSQL_DB: sdcqa
      MYSQL_USER: root
      MYSQL_PORT: 3306
    restart: on-failure
