version: '3.8'

services:
  mysql:
    container_name: docker-local-mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'sdcqa'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
    ports:
      - '3300:3300'
    volumes:
      - sql-db:/var/lib/mysql
volumes:
  sql-db:
